### ISSUE TITLE
Are there any plans to incorporate more elements?

### ISSUE THREAD

**Issue by matthewkuner** [usnistgov/ThreeBodyTB.jl#4]
I was wondering if there were plans to incorporate more elements into this code. Specifically, I'm personally interested in He, Ne, Ar, Kr, Xe, and most of the lanthanides/actinides

**Comment by kfgarrity** [comment]
Sorry, not at this time. There isn't a large demand for the noble gas elements in solids, and I don't treat the vdW terms very accurately anyways, so I'm not sure the point. 

I'd like to add lanthanides but handling the f-shell is not easy. I realize the following suggestion isn't fully satisfactory, but you can use La and Y/Sc as reasonable Lanthanide replacements for many (non-magnetic) purposes, or Sr for the +2 state.
